n = input('Digite algo:  ')
print('O tipo primitivo é: ', type(n))
print('Tem espaços: ', n.isspace())
print('Tem numeros: ', n.isnumeric())
print('É alpha numerico: ', n.isalpha())
print('É numerico: ', n.isalnum())
print('É decimal: ', n.isdecimal())
print('É printavel: ', n.isprintable())
print('Esta em letras minusculas: ', n.islower())
print('Esta em letras maiusculas: ', n.isupper())
print('Esta capitalizada: ', n.istitle())

